# Generated by Django 6.1 on 2026-08-27 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
            ],
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Barang')),
                ('stock', models.IntegerField(default=0, verbose_name='Stok Tersedia')),
                ('unit', models.CharField(max_length=50, verbose_name='Satuan (pcs, box, dll)')),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Harga Beli Terakhir')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='asset_request.assetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Jumlah')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pengajuan')),
                ('reason', models.TextField(verbose_name='Alasan / Keperluan')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('COMPLETED', 'Selesai (Sudah Diambil)')], default='PENDING', max_length=20)),
                ('photo_proof', models.ImageField(blank=True, null=True, upload_to='asset_proofs/', verbose_name='Foto Bukti')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='asset_signatures/', verbose_name='Tanda Tangan')),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assets', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='employees.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='asset_request.assetitem')),
            ],
        ),
    ]
