# Generated by Django 6.1 on 2026-08-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor HP'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin / Staff'), ('SALES', 'Sales'), ('DRIVER', 'Driver / Courier')], default='ADMIN', max_length=20, verbose_name='Kategori User'),
        ),
    ]
