# Generated by Django 6.1 on 2026-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin / Staff'), ('SALES', 'Sales'), ('DRIVER', 'Driver / Courier'), ('OPS', 'Operations / Gudang'), ('CS', 'Customer Service'), ('FINANCE', 'Finance / Keuangan'), ('MANAGER', 'Manager / SPV')], default='ADMIN', max_length=20, verbose_name='Kategori User'),
        ),
    ]
