# Generated by Django 6.1 on 2026-09-17 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='role',
            name='can_access_monitoring',
            field=models.BooleanField(default=False, verbose_name='Monitoring / Dashboard'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_access_vm',
            field=models.BooleanField(default=False, verbose_name='Vehicle Management'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_branch_scoped',
            field=models.BooleanField(default=False, help_text='Jika aktif, user dengan role ini hanya melihat data dari cabang-nya sendiri.', verbose_name='Batasi per Cabang'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_preset',
            field=models.BooleanField(default=False, help_text='Role bawaan tidak bisa dihapus dari sistem.', verbose_name='Role Bawaan Sistem'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_admin',
            field=models.BooleanField(default=False, verbose_name='Admin Panel'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_crm',
            field=models.BooleanField(default=False, verbose_name='CRM & Sales'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_finance',
            field=models.BooleanField(default=False, verbose_name='Finance'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_hr',
            field=models.BooleanField(default=False, verbose_name='HR & GA'),
        ),
        migrations.AlterField(
            model_name='role',
            name='can_access_operations',
            field=models.BooleanField(default=False, verbose_name='Operational'),
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('crm', 'CRM & Sales'), ('operations', 'Operational'), ('finance', 'Finance'), ('hr', 'HR & GA'), ('vm', 'Vehicle Management'), ('monitoring', 'Monitoring'), ('admin', 'Admin'), ('master', 'Data Master')], max_length=50)),
                ('codename', models.CharField(help_text="Identifier unik, e.g. 'operations.shipment.create', 'finance.invoice.approve'", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Label tampil, e.g. 'Buat Resi Baru'", max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='menu_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Izin Menu / Fitur',
                'verbose_name_plural': 'Izin Menu / Fitur',
                'ordering': ['module', 'codename'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permission tambahan di luar role utama. Untuk custom akses lintas divisi.', related_name='users_extra', to='accounts.menupermission', verbose_name='Izin Tambahan'),
        ),
    ]
