# Generated by Django 6.1 on 2026-09-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuVisibilitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Kode identifier unik, contoh: 'module_operations', 'menu_ops_pickup'", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nama tampilan menu / modul', max_length=200)),
                ('module_category', models.CharField(choices=[('master', 'Data Master'), ('crm', 'Sales & CRM'), ('operations', 'Operational'), ('finance', 'Finance'), ('hr', 'HR & GA'), ('vm', 'Vendor Management (VM)'), ('admin', 'Admin & Pengaturan')], max_length=50, verbose_name='Kategori Modul')),
                ('is_module_header', models.BooleanField(default=False, help_text='Jika dinonaktifkan, seluruh grup modul ini akan disembunyikan dari sidebar.', verbose_name='Header Modul Utama')),
                ('is_visible', models.BooleanField(default=True, help_text='Hapus centang untuk menyembunyikan menu/modul ini dari sistem.', verbose_name='Status Tampil (Aktif)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hidden_for_roles', models.ManyToManyField(blank=True, help_text='Pilih role yang TIDAK boleh melihat menu ini meskipun modulnya aktif.', related_name='hidden_menus', to='accounts.role', verbose_name='Sembunyikan Khusus Role Tertentu')),
            ],
            options={
                'verbose_name': 'Pengaturan Visibilitas Menu & Modul',
                'verbose_name_plural': 'Pengaturan Visibilitas Menu & Modul',
                'ordering': ['module_category', 'sort_order', 'code'],
            },
        ),
    ]
