# Generated by Django 6.1 on 2026-08-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rate Gaji per Hari')),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tunjangan Bulanan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_setting', to='employees.employee', verbose_name='Karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Bulan')),
                ('year', models.IntegerField(verbose_name='Tahun')),
                ('total_attendance', models.IntegerField(default=0, verbose_name='Total Kehadiran (Hari)')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Rate Gaji')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gaji Pokok')),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tunjangan')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Potongan')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gaji Bersih')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published (Bisa dilihat karyawan)'), ('PAID', 'Sudah Dibayar')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
