# Generated by Django 6.1 on 2026-08-10 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.BigIntegerField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KpiFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KpiSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sheet_type', models.CharField(choices=[('data', 'Data'), ('monthly_recap', 'Monthly Recap'), ('yearly_recap', 'Yearly Recap')], default='data', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='finance.kpifile')),
            ],
        ),
        migrations.CreateModel(
            name='KpiFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pickup', models.DateField(blank=True, null=True)),
                ('nama', models.CharField(blank=True, default='', max_length=255)),
                ('awb', models.CharField(blank=True, default='', max_length=255)),
                ('awb_sistem', models.CharField(blank=True, default='', max_length=255)),
                ('pengirim', models.CharField(blank=True, default='', max_length=255)),
                ('sales', models.CharField(blank=True, default='', max_length=255)),
                ('penerima', models.CharField(blank=True, default='', max_length=255)),
                ('service', models.CharField(blank=True, default='', max_length=255)),
                ('via', models.CharField(blank=True, default='', max_length=255)),
                ('aktual', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('vol', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('unit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('kubik', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('p', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('l', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('t', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('koil', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('harga', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('surcharge', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('packing', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('handling', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('penjualan', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('asal_pickup', models.CharField(blank=True, default='', max_length=255)),
                ('jenis_barang', models.CharField(blank=True, default='', max_length=255)),
                ('tujuan', models.CharField(blank=True, default='', max_length=255)),
                ('nama_vendor', models.CharField(blank=True, default='', max_length=255)),
                ('nama_vendor_ii', models.CharField(blank=True, default='', max_length=255)),
                ('nama_vendor_iii', models.CharField(blank=True, default='', max_length=255)),
                ('nama_vendor_iv', models.CharField(blank=True, default='', max_length=255)),
                ('vendor_i', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('vendor_ii', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('vendor_iii', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('vendor_iv', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('ops', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('asuransi', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('asuransi_jasindo', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('nilai_barang', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_biaya', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('idx_profit', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('formulas', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_data', to='finance.kpisheet')),
            ],
        ),
        migrations.CreateModel(
            name='CellStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.BigIntegerField()),
                ('field', models.CharField(max_length=255)),
                ('styles', models.JSONField(default=dict)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cell_styles', to='finance.kpisheet')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('pic', 'PIC'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('pic_id', models.IntegerField(default=-1)),
                ('allowed_columns', models.JSONField(blank=True, default=list, help_text='List kolom yang boleh diakses. Kosongkan jika semua.')),
                ('sheet_ids', models.JSONField(blank=True, default=list, help_text='List ID Sheet yang bisa diakses.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
