# Generated by Django 6.1 on 2026-08-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpifinance',
            name='aktual',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='asuransi',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='asuransi_jasindo',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='handling',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='harga',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='idx_profit',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='koil',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='kubik',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='l',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='nilai_barang',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='ops',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='packing',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='penjualan',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='surcharge',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='t',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='total_biaya',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='unit',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='vendor_i',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='vendor_ii',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='vendor_iii',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='vendor_iv',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='kpifinance',
            name='vol',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
    ]
