# Generated by Django 6.1 on 2026-08-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_kpifinance_aktual_alter_kpifinance_asuransi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.CharField(help_text='ID Kustomer dari CRM', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nama Kustomer / Perusahaan', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrmContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_quotation_id', models.CharField(help_text='ID Quotation dari CRM', max_length=50)),
                ('asal', models.CharField(blank=True, default='', max_length=100)),
                ('tujuan', models.CharField(blank=True, default='', max_length=100)),
                ('service', models.CharField(blank=True, default='', max_length=100)),
                ('via', models.CharField(blank=True, default='', max_length=50)),
                ('harga', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='finance.crmclient')),
            ],
            options={
                'unique_together': {('client', 'asal', 'tujuan', 'service', 'via')},
            },
        ),
    ]
