# Generated by Django 6.1 on 2026-08-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_crmclient_crmcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpifinance',
            name='crm_lead_id',
            field=models.CharField(blank=True, default='', help_text='ID Lead dari CRM, contoh: LD-0042', max_length=50),
        ),
        migrations.AddField(
            model_name='kpifinance',
            name='row_status',
            field=models.CharField(choices=[('new', 'Baru (dari CRM)'), ('vendor_filled', 'Vendor Diisi'), ('invoiced', 'Invoice Diisi'), ('completed', 'Selesai')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='kpifinance',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('crm', 'CRM Import'), ('import', 'File Import')], default='manual', max_length=20),
        ),
    ]
