# Generated by Django 6.1 on 2026-08-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_kpifinance_crm_lead_id_kpifinance_row_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcontract',
            name='penerima',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='kpifinance',
            name='ip_perusahaan',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
