# Generated by Django 6.1 on 2026-08-20 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_crmcontract_penerima_kpifinance_ip_perusahaan'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Invoice')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nama Klien / Perusahaan')),
                ('date_issued', models.DateField(auto_now_add=True, verbose_name='Tanggal Terbit')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Jatuh Tempo')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Pajak')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Tagihan')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Dibayar')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Terkirim (Sent)'), ('PARTIAL', 'Dibayar Sebagian (Partial)'), ('PAID', 'Lunas (Paid)'), ('VOID', 'Dibatalkan (Void)')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipments', models.ManyToManyField(blank=True, related_name='invoices', to='operations.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Nominal Bayar')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
            ],
        ),
    ]
