# Generated by Django 6.1 on 2026-08-21 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_invoice_paymentrecord'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Vendor')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama PIC')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. HP')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('service_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipe Layanan (Darat/Laut/Udara)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='organizations.branch', verbose_name='Cabang Terkait')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionVendorCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Biaya')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_costs', to='finance.kpifinance')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_costs', to='finance.vendor')),
            ],
        ),
    ]
