# Generated by Django 6.1 on 2026-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_branchwallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpifinance',
            name='row_status',
            field=models.CharField(choices=[('new', 'Baru (dari CRM)'), ('vendor_filled', 'Vendor Diisi'), ('invoiced', 'Invoice Diisi'), ('completed', 'Selesai'), ('voided', 'Dibatalkan (Void)')], default='completed', max_length=20),
        ),
    ]
