# Generated by Django 6.1 on 2026-08-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_kpifinance_row_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='materai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Materai'),
        ),
    ]
