# Generated by Django 6.1 on 2026-08-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_invoice_materai'),
        ('operations', '0011_shipment_contract_shipment_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpifinance',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_records', to='operations.shipment', verbose_name='Shipment Terkait'),
        ),
    ]
