# Generated by Django 6.1 on 2026-08-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_kpifinance_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='alamat_pelanggan',
            field=models.TextField(blank=True, default='', verbose_name='Alamat Pelanggan'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='biaya_kemasan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Biaya Kemasan / Packing Cost'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='biaya_kirim',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Biaya Kirim / Freight Cost'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='biaya_lain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Biaya Lain / Others Charges'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='biaya_tambahan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Biaya Tambahan (Surcharge & Handling)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_code',
            field=models.CharField(choices=[('PT AMANAH', 'PT Amanah Cargo Jaya Mandiri (Paketin Cargo)'), ('PT SARANA', 'Sarana Express (PT Sarana)'), ('PT SINERGI', 'Paketin Express (PT Sinergi)')], default='PT AMANAH', max_length=20, verbose_name='Perusahaan Penerbit'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='diskon',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Diskon'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='kode_pelanggan',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Kode Pelanggan'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='npwp',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='NPWP'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='periode_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Periode Akhir'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='periode_awal',
            field=models.DateField(blank=True, null=True, verbose_name='Periode Awal'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pic_invoice',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='PIC Invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='premi_asuransi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Premi Asuransi'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_ae',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sales (AE)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Biaya Kirim Dan Biaya Lain'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='PPN (1.1%)'),
        ),
    ]
