# Generated by Django 6.1 on 2026-08-26 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_invoice_alamat_pelanggan_invoice_biaya_kemasan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Draft Terbuka'),
        ),
        migrations.AddField(
            model_name='kpifinance',
            name='cost_verification_status',
            field=models.CharField(choices=[('pending', 'Belum Diverifikasi'), ('verified', 'Vendor Cost Terverifikasi')], default='pending', max_length=20, verbose_name='Status Verifikasi Vendor Cost'),
        ),
        migrations.AddField(
            model_name='kpifinance',
            name='linked_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_rows', to='finance.invoice', verbose_name='Invoice Terkait (display only)'),
        ),
    ]
