# Generated by Django 6.1 on 2026-08-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_invoice_is_open_kpifinance_cost_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='A/n Bank Account'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Rekening'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Bank'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('Door to Door', 'Door to Door'), ('Port to Port', 'Port to Port'), ('Door to Port', 'Door to Port'), ('Port to Door', 'Port to Door')], max_length=50, null=True, verbose_name='Tipe Pengiriman'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='npwp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NPWP'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_term_days',
            field=models.IntegerField(default=0, verbose_name='Invoice Payment Term (Days)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='primary_transport_mode',
            field=models.CharField(blank=True, choices=[('DARAT', 'DARAT'), ('LAUT', 'LAUT'), ('UDARA', 'UDARA'), ('KERETA', 'KERETA')], max_length=50, null=True, verbose_name='Moda Transportasi Utama'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='provided_darat',
            field=models.BooleanField(default=False, verbose_name='Darat'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='provided_kereta',
            field=models.BooleanField(default=False, verbose_name='Kereta'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='provided_laut',
            field=models.BooleanField(default=False, verbose_name='Laut'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='provided_udara',
            field=models.BooleanField(default=False, verbose_name='Udara'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status (Active)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telepon / HP'),
        ),
    ]
