# Generated by Django 6.1 on 2026-08-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_vendor_bank_account_name_vendor_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmclient',
            options={'managed': True},
        ),
    ]
