# Generated by Django 6.1 on 2026-09-21 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_vendor_created_at_vendor_created_by_and_more'),
        ('master', '0010_customer_branch_alter_bank_branch'),
        ('operations', '0033_shipment_with_do_balik_alter_shipment_status_and_more'),
        ('organizations', '0002_branch_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRevisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Nominal Sebelum')),
                ('new_total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Nominal Sesudah')),
                ('reason', models.TextField(verbose_name='Alasan Revisi / Penyesuaian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_logs', to='finance.invoice')),
                ('revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Direvisi Oleh')),
            ],
            options={
                'verbose_name': 'Log Revisi Invoice',
                'verbose_name_plural': 'Log Revisi Invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldp_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor LDP')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nama Klien / Perusahaan')),
                ('ldp_date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal LDP')),
                ('periode_awal', models.DateField(blank=True, null=True, verbose_name='Periode Awal')),
                ('periode_akhir', models.DateField(blank=True, null=True, verbose_name='Periode Akhir')),
                ('total_koli', models.IntegerField(default=0, verbose_name='Total Koli')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Berat (Kg)')),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Biaya Kirim')),
                ('total_surcharges', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Biaya Tambahan')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Nilai LDP')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Siap Tagih (Confirmed)'), ('INVOICED', 'Sudah Di-Invoice (Invoiced)'), ('CANCELLED', 'Dibatalkan (Cancelled)')], default='DRAFT', max_length=20, verbose_name='Status LDP')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldp_batches', to='organizations.branch', verbose_name='Cabang')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldp_batches', to='master.customer', verbose_name='Kustomer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ldps', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldps', to='finance.invoice', verbose_name='Invoice Terkait')),
            ],
            options={
                'verbose_name': 'Lembar Daftar Pengiriman (LDP)',
                'verbose_name_plural': 'Lembar Daftar Pengiriman (LDP)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LDPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(max_length=50, verbose_name='Nomor Resi / AWB')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Kirim')),
                ('sender_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Pengirim')),
                ('receiver_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Penerima')),
                ('origin', models.CharField(blank=True, default='', max_length=100, verbose_name='Asal')),
                ('destination', models.CharField(blank=True, default='', max_length=100, verbose_name='Tujuan')),
                ('service_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Layanan')),
                ('koli', models.IntegerField(default=1, verbose_name='Koli')),
                ('actual_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Berat Aktual (Kg)')),
                ('volume_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Berat Volume (Kg)')),
                ('chargeable_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Berat Ditagih (Kg)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarif per Kg')),
                ('freight_charge', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Ongkos Kirim Dasar')),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Biaya Asuransi')),
                ('packing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Biaya Packing')),
                ('handling_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Biaya Handling / Lainnya')),
                ('surcharges', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Surcharges')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Diskon')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Subtotal Tagihan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ldp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.ldp')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldp_items', to='operations.shipment')),
            ],
            options={
                'verbose_name': 'Item LDP',
                'verbose_name_plural': 'Item LDP',
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Nominal Bayar')),
                ('payment_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Waktu Transfer')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Referensi Transfer')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Bukti Transfer')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.bank', verbose_name='Bank Tujuan')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='finance.invoice')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi Oleh')),
            ],
            options={
                'verbose_name': 'Rekonsiliasi Pembayaran',
                'verbose_name_plural': 'Rekonsiliasi Pembayaran',
                'ordering': ['-created_at'],
            },
        ),
    ]
