# Generated by Django 6.1 on 2026-08-13 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('work_mode', models.CharField(choices=[('OFFICE', 'Office'), ('WFH', 'Work From Home'), ('FIELD', 'Field Worker'), ('REMOTE', 'Remote')], default='OFFICE', max_length=20)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('late_threshold_minutes', models.IntegerField(default=15)),
                ('gps_required', models.BooleanField(default=True)),
                ('allowed_radius_meters', models.IntegerField(default=200, help_text='0 means no restriction')),
                ('face_verification_required', models.BooleanField(default=True)),
                ('device_verification_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='organizations.branch')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], max_length=20)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EARLY_CHECKOUT', 'Early Checkout'), ('LEAVE', 'Leave'), ('SICK', 'Sick'), ('PERMISSION', 'Permission'), ('WFH', 'Work From Home'), ('BUSINESS_TRIP', 'Business Trip'), ('HOLIDAY', 'Holiday'), ('OVERTIME', 'Overtime'), ('PENDING', 'Pending'), ('SUSPICIOUS', 'Suspicious')], default='PRESENT', max_length=20)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_timestamp', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_accuracy', models.FloatField(blank=True, help_text='Accuracy in meters', null=True)),
                ('is_mock_location', models.BooleanField(default=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='employees.employee')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancepolicy')),
            ],
        ),
    ]
