# Generated by Django 6.1 on 2026-08-19 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Nama Perusahaan')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('phone', models.CharField(max_length=30, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('industry', models.CharField(choices=[('FARMASI', 'Farmasi & Kesehatan'), ('MANUFAKTUR', 'Manufaktur & Pabrik'), ('OTOMOTIF', 'Otomotif'), ('FMCG', 'FMCG (Fast Moving Consumer Goods)'), ('MAKANAN_MINUMAN', 'Makanan & Minuman (F&B)'), ('TEKSTIL', 'Tekstil & Garment'), ('ELEKTRONIK', 'Elektronik & Teknologi'), ('KONSTRUKSI', 'Konstruksi & Infrastruktur'), ('PERTAMBANGAN', 'Pertambangan & Energi'), ('PERTANIAN', 'Pertanian & Agribisnis'), ('KOSMETIK', 'Kosmetik & Kecantikan'), ('RETAIL', 'Retail & Grosir'), ('DISTRIBUTOR', 'Distributor Umum'), ('PERCETAKAN', 'Percetakan & Packaging'), ('FURNITURE', 'Furniture & Kerajinan'), ('LOGISTIK', 'Logistik & Transportasi'), ('E_COMMERCE', 'E-Commerce'), ('JASA', 'Jasa & Layanan'), ('OTHER', 'Lainnya (Other)')], max_length=100, null=True, verbose_name='Industri')),
                ('address', models.TextField(blank=True, default='', verbose_name='Alamat')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Kota')),
                ('province', models.CharField(blank=True, default='', max_length=100, verbose_name='Provinsi')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Kode Pos')),
                ('paketin_group', models.CharField(blank=True, choices=[('PT AMANAH', 'PAKETIN CARGO (PT AMANAH)'), ('PT SARANA', 'SARANA EXPRESS (PT SARANA)'), ('PT SINERGI', 'PAKETIN EXPRESS (PT SINERGI)')], max_length=50, null=True, verbose_name='Paketin Group')),
                ('npwp', models.CharField(blank=True, default='', max_length=30, verbose_name='NPWP')),
                ('website', models.URLField(blank=True, default='', max_length=255, verbose_name='Website')),
                ('customer_category', models.CharField(choices=[('PERUSAHAAN', 'Perusahaan'), ('PEMERINTAH', 'Pemerintah'), ('RUMAH_SAKIT', 'Rumah Sakit'), ('INDUSTRI', 'Industri'), ('DISTRIBUTOR', 'Distributor'), ('UMKM', 'UMKM'), ('PERORANGAN', 'Perorangan')], default='PERUSAHAAN', max_length=20, verbose_name='Kategori Pelanggan')),
                ('customer_status', models.CharField(choices=[('PROSPECT', 'Calon Pelanggan'), ('ACTIVE', 'Pelanggan Aktif'), ('INACTIVE', 'Pelanggan Tidak Aktif'), ('PRIORITY', 'Pelanggan Prioritas'), ('REGULAR', 'Pelanggan Tetap')], default='PROSPECT', max_length=20, verbose_name='Status Pelanggan')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='organizations.branch', verbose_name='Cabang')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Sales PIC')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_source', models.CharField(choices=[('WEBSITE', 'Website'), ('GOOGLE', 'Google'), ('INSTAGRAM', 'Instagram'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('WHATSAPP', 'WhatsApp'), ('MARKETPLACE', 'Marketplace'), ('REFERRAL', 'Rekomendasi / Referensi'), ('TELEMARKETING', 'Telemarketing'), ('EVENT', 'Acara / Pameran'), ('DIRECT_VISIT', 'Kunjungan Langsung'), ('EXISTING', 'Pelanggan Lama'), ('OTHER', 'Lainnya')], default='REFERRAL', max_length=20, verbose_name='Sumber Lead')),
                ('status', models.CharField(choices=[('NEW', 'Baru'), ('CONTACTED', 'Dihubungi'), ('QUALIFIED', 'Lolos Kualifikasi'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negosiasi'), ('WON', 'Menang / Berhasil'), ('LOST', 'Kalah / Gagal')], default='NEW', max_length=20, verbose_name='Status')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Estimasi Nilai (Rp)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('shipping_service', models.JSONField(blank=True, default=list, verbose_name='Jenis Pengiriman')),
                ('shipping_origin', models.CharField(blank=True, default='', max_length=150, verbose_name='Asal Pengiriman')),
                ('shipping_destination', models.CharField(blank=True, default='', max_length=150, verbose_name='Tujuan Pengiriman')),
                ('shipping_estimated_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estimasi Berat (kg)')),
                ('shipping_frequency', models.CharField(blank=True, default='', max_length=100, verbose_name='Frekuensi Pengiriman')),
                ('shipping_notes', models.TextField(blank=True, default='', verbose_name='Catatan Pengiriman')),
                ('responds_fast', models.CharField(choices=[('Y', 'Ya'), ('T', 'Tidak'), ('N', 'Netral')], default='N', max_length=1, verbose_name='Respon Cepat')),
                ('interested', models.CharField(choices=[('Y', 'Ya'), ('T', 'Tidak'), ('N', 'Netral')], default='N', max_length=1, verbose_name='Tertarik')),
                ('decision_maker', models.CharField(choices=[('Y', 'Ya'), ('T', 'Tidak'), ('N', 'Netral')], default='N', max_length=1, verbose_name='Decision Maker')),
                ('budget_available', models.CharField(choices=[('Y', 'Ya'), ('T', 'Tidak'), ('N', 'Netral')], default='N', max_length=1, verbose_name='Budget Tersedia')),
                ('competitor_exists', models.CharField(choices=[('Y', 'Ya'), ('T', 'Tidak'), ('N', 'Netral')], default='N', max_length=1, verbose_name='Ada Kompetitor')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Closing')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.client', verbose_name='Client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Sales PIC')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Kontrak')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Kontrak')),
                ('description', models.TextField(blank=True, default='', verbose_name='Deskripsi')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Nilai Kontrak (Rp)')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Berakhir')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Aktif'), ('EXPIRED', 'Kedaluwarsa'), ('TERMINATED', 'Dibatalkan'), ('RENEWED', 'Diperpanjang')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('terms', models.TextField(blank=True, default='', verbose_name='Syarat & Ketentuan')),
                ('penerima', models.CharField(blank=True, default='', max_length=255, verbose_name='Nama Penerima (Consignee)')),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='Dokumen Kontrak')),
                ('renewal_reminder_days', models.PositiveIntegerField(default=30, verbose_name='Pengingat Sebelum Berakhir (hari)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.client', verbose_name='Client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Sales PIC')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('VISIT', 'Visit'), ('MEETING', 'Meeting')], default='CALL', max_length=20, verbose_name='Jenis Aktivitas')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('result', models.TextField(blank=True, default='', verbose_name='Hasil')),
                ('next_followup', models.DateField(blank=True, null=True, verbose_name='Follow Up Selanjutnya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Sales PIC')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead', verbose_name='Lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panjang', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Panjang (cm)')),
                ('lebar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Lebar (cm)')),
                ('tinggi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Tinggi (cm)')),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Berat Aktual (kg)')),
                ('volumetric_weight', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Berat Volumetrik (kg)')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Asal')),
                ('destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tujuan')),
                ('service', models.JSONField(blank=True, default=list, verbose_name='Layanan')),
                ('insurance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Asuransi (Rp)')),
                ('packing', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Packing (Rp)')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='Jumlah Koli')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Harga per Kg (Rp)')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Diskon (Rp)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Total Harga (Rp)')),
                ('manual_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Harga (Manual)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quotations/attachments/', verbose_name='File Lampiran')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_APPROVAL', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('SENT', 'Terkirim ke Klien')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='crm.lead', verbose_name='Lead')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='Sales PIC')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight Actual (kg)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Colly')),
                ('panjang', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Panjang (cm)')),
                ('lebar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Lebar (cm)')),
                ('tinggi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Tinggi (cm)')),
                ('packing', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10, verbose_name='Packing')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description Item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('description', models.TextField(blank=True, default='', verbose_name='Deskripsi')),
                ('due_date', models.DateField(verbose_name='Tanggal')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='Waktu Reminder')),
                ('notify_before', models.IntegerField(choices=[(0, 'Tepat Waktu'), (5, '5 Menit Sebelumnya'), (15, '15 Menit Sebelumnya'), (30, '30 Menit Sebelumnya'), (60, '1 Jam Sebelumnya')], default=0, verbose_name='Ingatkan Sebelumnya')),
                ('completed', models.BooleanField(default=False, verbose_name='Selesai')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Sales PIC')),
            ],
            options={
                'ordering': ['due_date', 'reminder_time'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['owner', '-created_at'], name='crm_client_owner_i_095ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['branch', '-created_at'], name='crm_client_branch__c47fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company_name'], name='crm_client_company_19f044_idx'),
        ),
    ]
