# Generated by Django 6.1 on 2026-08-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_quotation_destination_coverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='crm.lead', verbose_name='Lead'),
        ),
    ]
