# Generated by Django 6.1 on 2026-08-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contract_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Set 0 jika tidak ada batas tagihan', max_digits=15, verbose_name='Plafon Piutang (Credit Limit)'),
        ),
    ]
