# Generated by Django 6.1 on 2026-09-14 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_client_credit_limit'),
        ('master', '0007_coverage_tlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='master_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_client', to='master.customer', verbose_name='Master Customer ERP'),
        ),
    ]
