# Generated by Django 6.1 on 2026-09-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_client_master_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_type',
            field=models.CharField(blank=True, choices=[('MASTER', 'Master'), ('SUB', 'Sub Account')], default='MASTER', max_length=50, verbose_name='Tipe Akun'),
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='client',
            name='divisi',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Divisi'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Transfer', 'Transfer'), ('Cash', 'Cash')], default='Transfer', max_length=50, verbose_name='Tipe Pembayaran'),
        ),
        migrations.AddField(
            model_name='client',
            name='pic_pickup',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='PIC Pickup'),
        ),
        migrations.AddField(
            model_name='client',
            name='pic_pickup_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telepon PIC Pickup'),
        ),
        migrations.AddField(
            model_name='client',
            name='term_of_payment',
            field=models.CharField(blank=True, choices=[('0', '0 Days (Cash)'), ('14', '14 Days'), ('30', '30 Days'), ('45', '45 Days'), ('60', '60 Days'), ('90', '90 Days')], default='0', max_length=50, verbose_name='Term Of Payment'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(max_length=255, verbose_name='Contact Person (PIC Akun)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Telepon PIC'),
        ),
    ]
