# Generated by Django 6.1 on 2026-08-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resi_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Resi')),
                ('sender_name', models.CharField(max_length=255, verbose_name='Nama Pengirim')),
                ('sender_phone', models.CharField(max_length=50, verbose_name='No. HP Pengirim')),
                ('sender_address', models.TextField(verbose_name='Alamat Pengirim')),
                ('receiver_name', models.CharField(max_length=255, verbose_name='Nama Penerima')),
                ('receiver_phone', models.CharField(max_length=50, verbose_name='No. HP Penerima')),
                ('receiver_address', models.TextField(verbose_name='Alamat Penerima')),
                ('origin', models.CharField(max_length=100, verbose_name='Kota Asal')),
                ('destination', models.CharField(max_length=100, verbose_name='Kota Tujuan')),
                ('service_type', models.CharField(choices=[('REG', 'Reguler'), ('EXP', 'Express'), ('CRG', 'Cargo')], default='REG', max_length=3, verbose_name='Tipe Layanan')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Berat Aktual (Kg)')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Panjang (cm)')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lebar (cm)')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tinggi (cm)')),
                ('volume_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Berat Volume (Kg)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Harga (Rp)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Menunggu Pickup'), ('IN_TRANSIT', 'Dalam Perjalanan'), ('DELIVERED', 'Terkirim'), ('RETURNED', 'Retur')], default='PENDING', max_length=20, verbose_name='Status Pengiriman')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Manifest')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Nama Driver/Supir')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Plat Kendaraan')),
                ('date', models.DateField(verbose_name='Tanggal Keberangkatan')),
                ('status', models.CharField(choices=[('PREPARING', 'Persiapan'), ('ON_THE_WAY', 'Dalam Perjalanan'), ('COMPLETED', 'Selesai')], default='PREPARING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipments', models.ManyToManyField(related_name='manifests', to='operations.shipment', verbose_name='Daftar Resi')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Menunggu Pickup'), ('IN_TRANSIT', 'Dalam Perjalanan'), ('DELIVERED', 'Terkirim'), ('RETURNED', 'Retur')], max_length=20)),
                ('location', models.CharField(max_length=255, verbose_name='Lokasi Saat Ini')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='operations.shipment')),
            ],
        ),
    ]
