# Generated by Django 6.1 on 2026-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='company_group',
            field=models.CharField(choices=[('PT AMANAH', 'PAKETIN CARGO (PT AMANAH)'), ('PT SARANA', 'SARANA EXPRESS (PT SARANA)'), ('PT SINERGI', 'PAKETIN EXPRESS (PT SINERGI)')], default='PT AMANAH', max_length=50, verbose_name='Perusahaan Pengirim (PT)'),
        ),
    ]
