# Generated by Django 6.1 on 2026-08-20 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('operations', '0002_shipment_company_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='company_group',
        ),
        migrations.AddField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client', verbose_name='Perusahaan/Klien Pengirim (Kontrak)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_name',
            field=models.CharField(max_length=255, verbose_name='Nama Penanggung Jawab (PIC)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_phone',
            field=models.CharField(max_length=50, verbose_name='No. HP PIC'),
        ),
    ]
