# Generated by Django 6.1 on 2026-08-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_shipment_company_group_shipment_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='sender_address',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat Pengirim'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Penanggung Jawab (PIC)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. HP PIC'),
        ),
    ]
