# Generated by Django 6.1 on 2026-08-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_coverage_is_verified_service_is_verified'),
        ('operations', '0004_alter_shipment_sender_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_destinations', to='master.coverage'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_manual_override',
            field=models.BooleanField(default=False, verbose_name='Input Manual (Bypass)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_origins', to='master.coverage'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.service'),
        ),
    ]
