# Generated by Django 6.1 on 2026-08-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_shipment_destination_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Tunai (POS Cash)'), ('CREDIT', 'Tagihan / Invoice (POS Credit)')], default='CASH', max_length=10, verbose_name='Tipe Pembayaran'),
        ),
    ]
