# Generated by Django 6.1 on 2026-08-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_vehicle'),
        ('operations', '0006_shipment_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='manifest',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Driver/Supir'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.vehicle', verbose_name='Kendaraan'),
        ),
    ]
