# Generated by Django 6.1 on 2026-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_remove_manifest_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Menunggu Pickup'), ('IN_TRANSIT', 'Dalam Perjalanan'), ('DELIVERED', 'Terkirim'), ('RETURNED', 'Retur'), ('VOID', 'Dibatalkan (Void)')], default='PENDING', max_length=20, verbose_name='Status Pengiriman'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Menunggu Pickup'), ('IN_TRANSIT', 'Dalam Perjalanan'), ('DELIVERED', 'Terkirim'), ('RETURNED', 'Retur'), ('VOID', 'Dibatalkan (Void)')], max_length=20),
        ),
    ]
