# Generated by Django 6.1 on 2026-08-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_shipment_status_alter_tracking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='chargeable_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Berat Ditagihkan (Chargeable)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='total_colly',
            field=models.IntegerField(default=1, verbose_name='Total Koli'),
        ),
        migrations.CreateModel(
            name='ShipmentColly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Barcode Koli')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Berat (Kg)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Menunggu Pickup'), ('IN_TRANSIT', 'Dalam Perjalanan'), ('DELIVERED', 'Terkirim'), ('RETURNED', 'Retur'), ('VOID', 'Dibatalkan (Void)')], default='PENDING', max_length=20)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collies', to='operations.shipment')),
            ],
        ),
    ]
