# Generated by Django 6.1 on 2026-08-22 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_shipment_chargeable_weight_shipment_total_colly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INBOUND_ORIGIN', 'Inbound (Gudang Asal)'), ('MANIFESTED', 'Manifested / Outbound'), ('IN_TRANSIT', 'Dalam Perjalanan (Transit Hub)'), ('INBOUND_DESTINATION', 'Inbound (Gudang Tujuan)'), ('DELIVERY_RUNSHEET', 'Dibawa Kurir (Run-Sheet)'), ('PARTIAL_DELIVERED', 'Terkirim Sebagian (Partial)'), ('DELIVERED', 'Terkirim (Full)'), ('RETURNED', 'Retur'), ('VOID', 'Dibatalkan (Void)')], default='PENDING', max_length=20, verbose_name='Status Pengiriman'),
        ),
        migrations.AlterField(
            model_name='shipmentcolly',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INBOUND_ORIGIN', 'Inbound (Gudang Asal)'), ('MANIFESTED', 'Manifested / Outbound'), ('IN_TRANSIT', 'Dalam Perjalanan (Transit Hub)'), ('INBOUND_DESTINATION', 'Inbound (Gudang Tujuan)'), ('DELIVERY_RUNSHEET', 'Dibawa Kurir (Run-Sheet)'), ('PARTIAL_DELIVERED', 'Terkirim Sebagian (Partial)'), ('DELIVERED', 'Terkirim (Full)'), ('RETURNED', 'Retur'), ('VOID', 'Dibatalkan (Void)')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INBOUND_ORIGIN', 'Inbound (Gudang Asal)'), ('MANIFESTED', 'Manifested / Outbound'), ('IN_TRANSIT', 'Dalam Perjalanan (Transit Hub)'), ('INBOUND_DESTINATION', 'Inbound (Gudang Tujuan)'), ('DELIVERY_RUNSHEET', 'Dibawa Kurir (Run-Sheet)'), ('PARTIAL_DELIVERED', 'Terkirim Sebagian (Partial)'), ('DELIVERED', 'Terkirim (Full)'), ('RETURNED', 'Retur'), ('VOID', 'Dibatalkan (Void)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight Actual (kg)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Colly')),
                ('panjang', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Panjang (cm)')),
                ('lebar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Lebar (cm)')),
                ('tinggi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Tinggi (cm)')),
                ('packing', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10, verbose_name='Packing')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description Item')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.shipment')),
            ],
        ),
    ]
