# Generated by Django 6.1 on 2026-08-24 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_client_credit_limit'),
        ('operations', '0010_alter_shipment_status_alter_shipmentcolly_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='crm.contract', verbose_name='Kontrak Terkait'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='crm.quotation', verbose_name='Penawaran (Quotation)'),
        ),
    ]
