# Generated by Django 6.1 on 2026-08-26 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_client_credit_limit'),
        ('master', '0004_coverage_is_active_price_is_active_vehicle_is_active'),
        ('operations', '0011_shipment_contract_shipment_quotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='manifest_type',
            field=models.CharField(choices=[('PICKUP', 'Pickup Manifest'), ('OUTGOING', 'Outgoing Manifest'), ('TRANSFER', 'Transfer Location Manifest'), ('DELIVERY', 'Delivery Runsheet')], default='OUTGOING', max_length=20, verbose_name='Tipe Manifest'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='do_balik_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal DO Balik'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Terima (POD)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_image',
            field=models.ImageField(blank=True, null=True, upload_to='pod_images/', verbose_name='Bukti Foto (POD)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Penerima (POD)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pickup / Diambil Kurir'), ('INBOUND_ORIGIN', 'Inbound (Gudang Asal)'), ('OUTGOING', 'Outgoing / Data Manifest'), ('TRANSFER', 'Transfer Location / Vendor Assignment'), ('INCOMING_DESTINATION', 'Incoming Destination (Gudang Tujuan)'), ('DELIVERY', 'Delivery / Dibawa Kurir'), ('POD', 'Terkirim (POD Inputted)'), ('POD_BALIK', 'POD Balik (Selesai)'), ('PARTIAL_DELIVERED', 'Terkirim Sebagian (Partial)'), ('RETURNED', 'Retur'), ('VOID', 'Dibatalkan (Void)')], default='PENDING', max_length=20, verbose_name='Status Pengiriman'),
        ),
        migrations.AlterField(
            model_name='shipmentcolly',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pickup / Diambil Kurir'), ('INBOUND_ORIGIN', 'Inbound (Gudang Asal)'), ('OUTGOING', 'Outgoing / Data Manifest'), ('TRANSFER', 'Transfer Location / Vendor Assignment'), ('INCOMING_DESTINATION', 'Incoming Destination (Gudang Tujuan)'), ('DELIVERY', 'Delivery / Dibawa Kurir'), ('POD', 'Terkirim (POD Inputted)'), ('POD_BALIK', 'POD Balik (Selesai)'), ('PARTIAL_DELIVERED', 'Terkirim Sebagian (Partial)'), ('RETURNED', 'Retur'), ('VOID', 'Dibatalkan (Void)')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pickup / Diambil Kurir'), ('INBOUND_ORIGIN', 'Inbound (Gudang Asal)'), ('OUTGOING', 'Outgoing / Data Manifest'), ('TRANSFER', 'Transfer Location / Vendor Assignment'), ('INCOMING_DESTINATION', 'Incoming Destination (Gudang Tujuan)'), ('DELIVERY', 'Delivery / Dibawa Kurir'), ('POD', 'Terkirim (POD Inputted)'), ('POD_BALIK', 'POD Balik (Selesai)'), ('PARTIAL_DELIVERED', 'Terkirim Sebagian (Partial)'), ('RETURNED', 'Retur'), ('VOID', 'Dibatalkan (Void)')], max_length=20),
        ),
        migrations.CreateModel(
            name='PickupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(verbose_name='Tanggal Pickup')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='Waktu Pickup')),
                ('reff_doc_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reff Doc. No (PR)')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('req_packing', models.BooleanField(default=False, verbose_name='Req. Packing?')),
                ('insurance', models.BooleanField(default=False, verbose_name='Insurance?')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('pic_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='PIC Pickup')),
                ('pic_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='PIC Phone')),
                ('pickup_address', models.TextField(blank=True, null=True, verbose_name='Pickup Address')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight')),
                ('colly', models.IntegerField(default=1, verbose_name='Colly')),
                ('shipment_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shipment Type')),
                ('description_item', models.TextField(blank=True, null=True, verbose_name='Description Item')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='pickup_docs/', verbose_name='File Upload')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED_TO_DRIVER', 'Assigned to Driver'), ('PICKED_UP', 'Picked Up'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client', verbose_name='Customer')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Driver Pickup')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.vehicle', verbose_name='Req. Vehicle')),
            ],
        ),
    ]
