# Generated by Django 6.1 on 2026-08-26 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_invoice_is_open_kpifinance_cost_verification_status_and_more'),
        ('operations', '0012_manifest_manifest_type_shipment_do_balik_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='flight_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Flight No / SMU (Air Freight)'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.vendor', verbose_name='Vendor Ekspedisi'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='vendor_ref_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Resi / SPK Vendor'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='vessel_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Kapal / No. BL (Sea Freight)'),
        ),
    ]
