# Generated by Django 6.1 on 2026-08-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_manifest_flight_no_manifest_vendor_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='actual_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual Weight Manifest'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifests', to='organizations.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='colly_cmo',
            field=models.IntegerField(default=0, verbose_name='Colly CMO'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='commodity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Commodity'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description / Reason'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='destination_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tlc / City Destination'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='is_bypass',
            field=models.BooleanField(default=False, verbose_name='Outgoing By Pass'),
        ),
    ]
