# Generated by Django 6.1 on 2026-08-26 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_invoice_is_open_kpifinance_cost_verification_status_and_more'),
        ('operations', '0014_manifest_actual_weight_manifest_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Arrival Date'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Arrival Time'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Departure Time'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Moda Transportasi'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='vendor_middle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifest_vendor_middle', to='finance.vendor', verbose_name='Vendor Middle'),
        ),
    ]
