# Generated by Django 6.1 on 2026-08-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_manifest_arrival_date_manifest_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['-timestamp']},
        ),
        migrations.CreateModel(
            name='InboundSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbound_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Inbound')),
                ('location', models.CharField(max_length=255, verbose_name='Lokasi Gudang')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipments', models.ManyToManyField(related_name='inbound_sessions', to='operations.shipment', verbose_name='Daftar Resi Inbound')),
            ],
        ),
    ]
