# Generated by Django 6.1 on 2026-08-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_alter_tracking_options_inboundsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='pickup_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nomor Pickup'),
        ),
    ]
