# Generated by Django 6.1 on 2026-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_pickuporder_pickup_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='pickup_orders',
            field=models.ManyToManyField(blank=True, related_name='pickup_manifests', to='operations.pickuporder', verbose_name='Daftar Pickup'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='shipments',
            field=models.ManyToManyField(blank=True, related_name='manifests', to='operations.shipment', verbose_name='Daftar Resi'),
        ),
    ]
