# Generated by Django 6.1 on 2026-08-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_manifest_pickup_orders_alter_manifest_shipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='vehicle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Req. Vehicle'),
        ),
    ]
