# Generated by Django 6.1 on 2026-08-28 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_alter_pickuporder_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='cod_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='COD Value'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='description_item',
            field=models.TextField(blank=True, null=True, verbose_name='Description Item'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='handling_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Handling Cost'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='input_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Import Excel')], default='MANUAL', max_length=10, verbose_name='Tipe Input'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='insurance_type',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=5, verbose_name='Insurance?'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_cod',
            field=models.BooleanField(default=False, verbose_name='COD?'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='item_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Item Value (Rp)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='packing_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Biaya Packing (Rp)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_number_ref',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pickup No (Ref)'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_attention',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Receiver Attention'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota Penerima'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan Penerima'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kode Pos Penerima'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference No'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_attention',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipper Attention'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kota Pengirim'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan Pengirim'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kode Pos Pengirim'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type_detail',
            field=models.CharField(choices=[('PACKAGE', 'Package'), ('DOCUMENT', 'Document'), ('PALLET', 'Pallet')], default='PACKAGE', max_length=20, verbose_name='Shipment Type'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipper_same_as_pickup',
            field=models.BooleanField(default=False, verbose_name='Detail Shipper = Detail Pickup'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='special_instruction',
            field=models.TextField(blank=True, null=True, verbose_name='Special Instruction'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='surcharge_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Surcharge Cost'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='surcharge_type',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=5, verbose_name='Surcharge?'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='service_type',
            field=models.CharField(choices=[('REG', 'Reguler'), ('ODS', 'One Day Service'), ('SDS', 'Same Day Service'), ('RD', 'Reguler Darat'), ('RL', 'Reguler Laut'), ('RUC', 'Reguler Udara Cargo'), ('RU', 'Reguler Udara'), ('TRK', 'Trucking')], default='REG', max_length=5, verbose_name='Tipe Layanan'),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='packing',
            field=models.CharField(choices=[('NONE', 'Tidak Ada'), ('FULL', 'Packing Full'), ('KAYU', 'Packing Kayu'), ('BUSA_KARDUS', 'Packing Busa/Kardus')], default='NONE', max_length=20, verbose_name='Packing'),
        ),
    ]
