# Generated by Django 6.1 on 2026-09-03 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_coverage_tlc'),
        ('operations', '0020_shipment_cod_value_shipment_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL, verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.customer', verbose_name='Perusahaan/Klien Pengirim (Kontrak)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_type_detail',
            field=models.CharField(choices=[('PACKAGE', 'Package'), ('DOCUMENT', 'Document')], default='PACKAGE', max_length=20, verbose_name='Shipment Type'),
        ),
    ]
