# Generated by Django 6.1 on 2026-09-05 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_alter_pickuporder_client_alter_pickuporder_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifests_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
    ]
