# Generated by Django 6.1 on 2026-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_manifest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='pic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PIC / Penanggung Jawab'),
        ),
    ]
