# Generated by Django 6.1 on 2026-09-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_alter_tracking_options_tracking_occurred_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Persiapan'), ('ON_THE_WAY', 'Dalam Perjalanan'), ('COMPLETED', 'Selesai'), ('CANCELLED', 'Void')], default='PREPARING', max_length=20),
        ),
    ]
