# Generated by Django 6.1 on 2026-09-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_add_transit_status_and_migrate_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pickup / Diambil Kurir'), ('INBOUND_ORIGIN', 'Inbound (Gudang Asal)'), ('OUTGOING', 'Outgoing / Data Manifest'), ('TRANSFER', 'Transfer Location'), ('TRANSIT', 'Transit'), ('INCOMING_DESTINATION', 'Incoming Destination (Gudang Tujuan)'), ('DELIVERY', 'Delivery / Dibawa Kurir'), ('POD', 'Terkirim (POD Inputted)'), ('POD_BALIK', 'POD Balik (Selesai)'), ('PARTIAL_DELIVERED', 'Terkirim Sebagian (Partial)'), ('RETURNED', 'Retur'), ('VOID', 'Void')], default='PENDING', max_length=20, verbose_name='Status Pengiriman'),
        ),
        migrations.AlterField(
            model_name='shipmentcolly',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pickup / Diambil Kurir'), ('INBOUND_ORIGIN', 'Inbound (Gudang Asal)'), ('OUTGOING', 'Outgoing / Data Manifest'), ('TRANSFER', 'Transfer Location'), ('TRANSIT', 'Transit'), ('INCOMING_DESTINATION', 'Incoming Destination (Gudang Tujuan)'), ('DELIVERY', 'Delivery / Dibawa Kurir'), ('POD', 'Terkirim (POD Inputted)'), ('POD_BALIK', 'POD Balik (Selesai)'), ('PARTIAL_DELIVERED', 'Terkirim Sebagian (Partial)'), ('RETURNED', 'Retur'), ('VOID', 'Void')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pickup / Diambil Kurir'), ('INBOUND_ORIGIN', 'Inbound (Gudang Asal)'), ('OUTGOING', 'Outgoing / Data Manifest'), ('TRANSFER', 'Transfer Location'), ('TRANSIT', 'Transit'), ('INCOMING_DESTINATION', 'Incoming Destination (Gudang Tujuan)'), ('DELIVERY', 'Delivery / Dibawa Kurir'), ('POD', 'Terkirim (POD Inputted)'), ('POD_BALIK', 'POD Balik (Selesai)'), ('PARTIAL_DELIVERED', 'Terkirim Sebagian (Partial)'), ('RETURNED', 'Retur'), ('VOID', 'Void')], max_length=20),
        ),
    ]
