# Generated by Django 6.1 on 2026-09-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_alter_shipment_status_alter_shipmentcolly_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PODAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pod_media/%Y/%m/', verbose_name='File Bukti POD')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Foto'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_attachments', to='operations.shipment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
