# Generated by Django 6.1 on 2026-09-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_podattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Disembunyikan'),
        ),
    ]
