# Generated by Django 6.1 on 2026-09-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_manifest_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundsession',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Disembunyikan'),
        ),
        migrations.AddField(
            model_name='inboundsession',
            name='is_void',
            field=models.BooleanField(default=False, verbose_name='Void'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Disembunyikan'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Disembunyikan'),
        ),
    ]
