# Generated by Django 6.1 on 2026-09-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_inboundsession_is_hidden_inboundsession_is_void_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracking',
            options={'ordering': ['-step_order', '-occurred_at', '-timestamp']},
        ),
        migrations.AddField(
            model_name='tracking',
            name='step_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Urutan Langkah'),
        ),
    ]
