# Generated by Django 6.1 on 2026-09-21 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_alter_tracking_options_tracking_step_order'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='with_do_balik',
            field=models.BooleanField(default=False, verbose_name='DO Balik?'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pick Up'), ('INBOUND_ORIGIN', 'Inbound Origin'), ('OUTGOING', 'Outgoing'), ('TRANSFER', 'Transfer Location'), ('TRANSIT', 'Transit'), ('INCOMING_DESTINATION', 'Incoming Destination'), ('DELIVERY', 'Delivery'), ('POD', 'POD'), ('POD_BALIK', 'POD Balik'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('RETURNED', 'Returned'), ('VOID', 'Void')], default='PENDING', max_length=20, verbose_name='Status Pengiriman'),
        ),
        migrations.AlterField(
            model_name='shipmentcolly',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pick Up'), ('INBOUND_ORIGIN', 'Inbound Origin'), ('OUTGOING', 'Outgoing'), ('TRANSFER', 'Transfer Location'), ('TRANSIT', 'Transit'), ('INCOMING_DESTINATION', 'Incoming Destination'), ('DELIVERY', 'Delivery'), ('POD', 'POD'), ('POD_BALIK', 'POD Balik'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('RETURNED', 'Returned'), ('VOID', 'Void')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pick Up'), ('INBOUND_ORIGIN', 'Inbound Origin'), ('OUTGOING', 'Outgoing'), ('TRANSFER', 'Transfer Location'), ('TRANSIT', 'Transit'), ('INCOMING_DESTINATION', 'Incoming Destination'), ('DELIVERY', 'Delivery'), ('POD', 'POD'), ('POD_BALIK', 'POD Balik'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('RETURNED', 'Returned'), ('VOID', 'Void')], max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentPouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pouch_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor Pouch DO')),
                ('courier_service', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurir / Ekspedisi Pengirim')),
                ('airwaybill_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Resi Pengiriman Dokumen')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dalam Perjalanan (Dispatched)'), ('RECEIVED', 'Diterima di Hub Asal (Received)'), ('COMPLETED', 'Selesai / Diserahkan ke Klien (Completed)')], default='DRAFT', max_length=20, verbose_name='Status Pouch')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('handover_to_client_at', models.DateTimeField(blank=True, null=True)),
                ('handover_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Serah Terima Klien')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pouches', to=settings.AUTH_USER_MODEL)),
                ('dest_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pouch_destinations', to='organizations.branch', verbose_name='Hub Penerima (Asal Kirim)')),
                ('origin_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pouch_origins', to='organizations.branch', verbose_name='Hub Pengirim (Tujuan Kirim)')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_pouches', to=settings.AUTH_USER_MODEL)),
                ('shipments', models.ManyToManyField(blank=True, related_name='document_pouches', to='operations.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rto_number', models.CharField(max_length=50, unique=True, verbose_name='Nomor RTO')),
                ('reason', models.CharField(choices=[('BAD_ADDRESS', 'Alamat Tidak Lengkap / Tidak Ditemukan'), ('RECIPIENT_REFUSED', 'Penerima Menolak Menerima Paket'), ('FAILED_3X', 'Gagal Antar 3x (Penerima Tidak Ada di Tempat)'), ('COD_REJECTED', 'Penerima Batal Beli / Tidak Mau Bayar COD'), ('DAMAGED', 'Barang Rusak di Perjalanan'), ('OTHER', 'Lainnya')], max_length=50, verbose_name='Alasan Retur')),
                ('reason_detail', models.TextField(blank=True, null=True, verbose_name='Keterangan Detail Gagal Antar')),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='return_evidence/', verbose_name='Foto Bukti Gagal Antar')),
                ('status', models.CharField(choices=[('HOLD_DESTINATION', 'Tertahan di Hub Tujuan (Undelivered)'), ('CONFIRM_SHIPPER', 'Menunggu Konfirmasi Shipper / CS'), ('APPROVED_RTO', 'Disetujui Retur ke Asal (Approved RTO)'), ('IN_TRANSIT_RTO', 'Dalam Perjalanan Kembali ke Asal (RTO Linehaul)'), ('RECEIVED_ORIGIN', 'Diterima di Hub Asal'), ('RETURNED_TO_SHIPPER', 'Selesai / Diserahkan ke Pengirim'), ('CANCELLED_REDELIVERED', 'Batal Retur (Diantar Ulang Berhasil)')], default='HOLD_DESTINATION', max_length=30, verbose_name='Status Retur')),
                ('cs_notes', models.TextField(blank=True, null=True, verbose_name='Catatan CS / Keputusan Shipper')),
                ('rto_manifest_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='No Manifest RTO')),
                ('return_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Biaya Ongkir Retur')),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_returns', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='operations.shipment', verbose_name='Shipment / AWB')),
            ],
        ),
    ]
