# Generated by Django 6.1 on 2026-09-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_shipment_with_do_balik_alter_shipment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnshipment',
            name='action_type',
            field=models.CharField(choices=[('PENDING', 'Belum Ditentukan (Tab A: Laporan Masuk)'), ('REDELIVER', 'Kirim Ulang (Tab B: Kirim Ulang)'), ('RETURN_TO_ORIGIN', 'Kembali ke Pengirim (Tab C: Retur Pengirim)')], default='PENDING', max_length=30, verbose_name='Tindakan Keputusan'),
        ),
        migrations.AddField(
            model_name='returnshipment',
            name='attempt_count',
            field=models.IntegerField(default=1, verbose_name='Percobaan ke-'),
        ),
        migrations.AddField(
            model_name='returnshipment',
            name='scheduled_redelivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Jadwal Kirim Ulang'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_attempts',
            field=models.IntegerField(default=0, verbose_name='Jumlah Percobaan Antar'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='failed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Gagal Antar'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='failed_image',
            field=models.ImageField(blank=True, null=True, upload_to='pod_failed/', verbose_name='Bukti Foto Gagal Antar'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='failed_note',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan Gagal Antar'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='failed_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alasan Gagal Antar'),
        ),
        migrations.AlterField(
            model_name='returnshipment',
            name='reason',
            field=models.CharField(choices=[('BAD_ADDRESS', 'Alamat Tidak Lengkap / Tidak Ditemukan'), ('RECIPIENT_NOT_HOME', 'Penerima Tidak di Tempat / Rumah Tutup'), ('RECIPIENT_REFUSED', 'Penerima Menolak Menerima Paket'), ('PHONE_UNREACHABLE', 'Nomor Telepon / HP Tidak Aktif'), ('FAILED_3X', 'Gagal Antar 3x (Penerima Tidak Ada)'), ('COD_REJECTED', 'Penerima Batal Beli / Tidak Mau Bayar COD'), ('DAMAGED', 'Barang Rusak di Perjalanan'), ('FORCE_MAJEURE', 'Kendala Akses / Bencana / Force Majeure'), ('OTHER', 'Lainnya')], max_length=50, verbose_name='Alasan Retur / Gagal'),
        ),
        migrations.AlterField(
            model_name='returnshipment',
            name='status',
            field=models.CharField(choices=[('HOLD_DESTINATION', 'Laporan Masuk / Tertahan di Hub Tujuan (Pending Action)'), ('SCHEDULED_REDELIVERY', 'Dijadwalkan Kirim Ulang (Re-delivery)'), ('CONFIRM_SHIPPER', 'Menunggu Konfirmasi Shipper / CS'), ('APPROVED_RTO', 'Disetujui Retur ke Pengirim (Approved RTO)'), ('IN_TRANSIT_RTO', 'Dalam Perjalanan Kembali ke Asal (RTO Linehaul)'), ('RECEIVED_ORIGIN', 'Diterima di Hub Asal'), ('RETURNED_TO_SHIPPER', 'Selesai / Diserahkan ke Pengirim'), ('CANCELLED_REDELIVERED', 'Selesai Terkirim (Antar Ulang Berhasil)')], default='HOLD_DESTINATION', max_length=30, verbose_name='Status Retur'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pick Up'), ('INBOUND_ORIGIN', 'Inbound Origin'), ('OUTGOING', 'Outgoing'), ('TRANSFER', 'Transfer Location'), ('TRANSIT', 'Transit'), ('INCOMING_DESTINATION', 'Incoming Destination'), ('DELIVERY', 'Delivery'), ('DELIVERY_FAILED', 'Gagal Antar (Undelivered)'), ('POD', 'POD'), ('POD_BALIK', 'POD Balik'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('RETURNED', 'Returned'), ('VOID', 'Void')], default='PENDING', max_length=20, verbose_name='Status Pengiriman'),
        ),
        migrations.AlterField(
            model_name='shipmentcolly',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pick Up'), ('INBOUND_ORIGIN', 'Inbound Origin'), ('OUTGOING', 'Outgoing'), ('TRANSFER', 'Transfer Location'), ('TRANSIT', 'Transit'), ('INCOMING_DESTINATION', 'Incoming Destination'), ('DELIVERY', 'Delivery'), ('DELIVERY_FAILED', 'Gagal Antar (Undelivered)'), ('POD', 'POD'), ('POD_BALIK', 'POD Balik'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('RETURNED', 'Returned'), ('VOID', 'Void')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKUP', 'Pick Up'), ('INBOUND_ORIGIN', 'Inbound Origin'), ('OUTGOING', 'Outgoing'), ('TRANSFER', 'Transfer Location'), ('TRANSIT', 'Transit'), ('INCOMING_DESTINATION', 'Incoming Destination'), ('DELIVERY', 'Delivery'), ('DELIVERY_FAILED', 'Gagal Antar (Undelivered)'), ('POD', 'POD'), ('POD_BALIK', 'POD Balik'), ('PARTIAL_DELIVERED', 'Partial Delivered'), ('RETURNED', 'Returned'), ('VOID', 'Void')], max_length=20),
        ),
    ]
