# Generated by Django 6.1 on 2026-09-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Atas Nama Rekening'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomor Rekening'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Bank'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Berakhir Kontrak'),
        ),
        migrations.AddField(
            model_name='employee',
            name='document_contract',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/contracts/', verbose_name='Dokumen Kontrak / SK'),
        ),
        migrations.AddField(
            model_name='employee',
            name='document_ktp',
            field=models.FileField(blank=True, null=True, upload_to='employee_docs/ktp/', verbose_name='Dokumen KTP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Kontak Darurat'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. HP Darurat'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hubungan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nik',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIK / No. KTP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='npwp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NPWP'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Bergabung'),
        ),
    ]
