# Generated by Django 6.1 on 2026-08-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Bank')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Bank')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='No Rekening')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Atas Nama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, verbose_name='Kecamatan (District)')),
                ('city', models.CharField(max_length=100, verbose_name='Kota/Kabupaten')),
                ('province', models.CharField(max_length=100, verbose_name='Provinsi')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kode Pos')),
                ('is_covered', models.BooleanField(default=True, verbose_name='Terjangkau Layanan')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode Layanan')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Layanan (Contoh: REG, ONS, CARGO)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Harga per Kg')),
                ('min_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Min Berat (Kg)')),
                ('estimated_days', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estimasi Tiba (Hari)')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_destinations', to='master.coverage', verbose_name='Tujuan')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_origins', to='master.coverage', verbose_name='Asal')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.service', verbose_name='Layanan')),
            ],
        ),
    ]
