# Generated by Django 6.1 on 2026-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Terverifikasi'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='Terverifikasi'),
        ),
    ]
