# Generated by Django 6.1 on 2026-08-22 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_coverage_is_verified_service_is_verified'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plat Kendaraan')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='Tipe Kendaraan')),
                ('brand_model', models.CharField(blank=True, max_length=100, verbose_name='Merek & Model')),
                ('capacity_kg', models.IntegerField(default=0, verbose_name='Kapasitas (Kg)')),
                ('capacity_cbm', models.IntegerField(default=0, verbose_name='Kapasitas (CBM)')),
                ('registration_expiry', models.DateField(blank=True, null=True, verbose_name='Masa Berlaku STNK')),
                ('kir_expiry', models.DateField(blank=True, null=True, verbose_name='Masa Berlaku KIR')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('MAINTENANCE', 'Perawatan'), ('INACTIVE', 'Tidak Aktif')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.branch', verbose_name='Cabang Operasional')),
            ],
        ),
    ]
