# Generated by Django 6.1 on 2026-09-02 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_coverage_is_active_price_is_active_vehicle_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode Provinsi')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Provinsi')),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('MASTER', 'Master'), ('SUB', 'Sub Account')], max_length=50, verbose_name='Tipe Akun')),
                ('customer_code', models.CharField(max_length=50, unique=True, verbose_name='Kode Master Customer')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Customer')),
                ('divisi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Divisi')),
                ('type_industry', models.CharField(max_length=100, verbose_name='Tipe Industri')),
                ('effective_start_date', models.DateField(blank=True, null=True, verbose_name='Mulai Berlaku')),
                ('effective_end_date', models.DateField(blank=True, null=True, verbose_name='Akhir Berlaku')),
                ('pic_account', models.CharField(max_length=100, verbose_name='PIC Akun')),
                ('pic_phone', models.CharField(max_length=50, verbose_name='Telepon PIC')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('api_integration', models.BooleanField(default=False, verbose_name='Integrasi API')),
                ('city', models.CharField(max_length=100, verbose_name='Kota')),
                ('office_address', models.TextField(verbose_name='Alamat Kantor')),
                ('district', models.CharField(max_length=100, verbose_name='Kecamatan')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kode POS')),
                ('term_of_payment', models.CharField(choices=[('0', '0 Days'), ('14', '14 Days'), ('30', '30 Days'), ('45', '45 Days'), ('60', '60 Days'), ('90', '90 Days')], default='0', max_length=50, verbose_name='Term Of Payment')),
                ('payment_type', models.CharField(max_length=50, verbose_name='Tipe Pembayaran')),
                ('virtual_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='Virtual Account')),
                ('ppn_percentage', models.CharField(choices=[('1.2', '1.2 %'), ('12', '12 %'), ('1', '1 %'), ('1.1', '1.1 %')], default='1.2', max_length=10, verbose_name='PPN %')),
                ('npwp', models.CharField(max_length=50, verbose_name='NPWP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Aktif', 'Aktif')], default='Draft', max_length=50, verbose_name='Status')),
                ('min_premi_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Minimal Premi Asuransi')),
                ('email_invoice', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Invoice')),
                ('handling_type_shipment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipe Penanganan (Handling)')),
                ('take_photo_pod', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ambil Foto POD')),
                ('bank_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.bank', verbose_name='Transfer Bank')),
                ('sales', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'SALES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sales')),
            ],
        ),
        migrations.CreateModel(
            name='Regency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Kode Kab/Kota')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Kab/Kota')),
                ('type', models.CharField(choices=[('KABUPATEN', 'Kabupaten'), ('KOTA', 'Kota')], default='KABUPATEN', max_length=20, verbose_name='Tipe')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regencies', to='master.province', verbose_name='Provinsi')),
            ],
            options={
                'verbose_name': 'Kabupaten/Kota',
                'verbose_name_plural': 'Kabupaten/Kota',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Kode Kecamatan')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Kecamatan')),
                ('regency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='master.regency', verbose_name='Kab/Kota')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode Kel/Desa')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Kel/Desa')),
                ('type', models.CharField(choices=[('KELURAHAN', 'Kelurahan'), ('DESA', 'Desa')], default='DESA', max_length=20, verbose_name='Tipe')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='master.district', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan/Desa',
                'verbose_name_plural': 'Kelurahan/Desa',
                'ordering': ['name'],
            },
        ),
    ]
