# Generated by Django 6.1 on 2026-09-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_province_customer_regency_district_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='divisor',
            field=models.IntegerField(default=5000, verbose_name='Pembagi Volume (Rumus Berat)'),
        ),
    ]
