# Generated by Django 6.1 on 2026-09-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_service_divisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='tlc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kode TLC (Tiga Huruf)'),
        ),
    ]
