# Generated by Django 6.1 on 2026-09-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_coverage_tlc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alamat Bank'),
        ),
        migrations.AddField(
            model_name='bank',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cabang Bank'),
        ),
        migrations.AddField(
            model_name='customer',
            name='insurance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Persentase Asuransi %'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_invoice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telepon PIC Invoice'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pic_invoice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PIC Invoice'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pic_pickup',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='PIC Pickup'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pic_pickup_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telepon PIC Pickup'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pickup_same_as_office',
            field=models.BooleanField(default=True, verbose_name='Detail Pickup Sama Dengan Kantor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='with_pod_resi',
            field=models.BooleanField(default=False, verbose_name='Dengan POD / Resi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('MASTER', 'Master'), ('SUB', 'Sub Account')], default='MASTER', max_length=50, verbose_name='Tipe Akun'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Cash', 'Cash')], default='Transfer', max_length=50, verbose_name='Tipe Pembayaran'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='type_industry',
            field=models.CharField(choices=[('FARMASI', 'Farmasi & Kesehatan'), ('MANUFAKTUR', 'Manufaktur & Pabrik'), ('OTOMOTIF', 'Otomotif'), ('FMCG', 'FMCG (Fast Moving Consumer Goods)'), ('MAKANAN_MINUMAN', 'Makanan & Minuman (F&B)'), ('TEKSTIL', 'Tekstil & Garment'), ('ELEKTRONIK', 'Elektronik & Teknologi'), ('KONSTRUKSI', 'Konstruksi & Infrastruktur'), ('PERTAMBANGAN', 'Pertambangan & Energi'), ('PERTANIAN', 'Pertanian & Agribisnis'), ('KOSMETIK', 'Kosmetik & Kecantikan'), ('RETAIL', 'Retail & Grosir'), ('DISTRIBUTOR', 'Distributor Umum'), ('PERCETAKAN', 'Percetakan & Packaging'), ('FURNITURE', 'Furniture & Kerajinan'), ('LOGISTIK', 'Logistik & Transportasi'), ('E_COMMERCE', 'E-Commerce'), ('JASA', 'Jasa & Layanan'), ('OTHER', 'Lainnya (Other)')], default='OTHER', max_length=100, verbose_name='Tipe Industri'),
        ),
    ]
