# Generated by Django 6.1 on 2026-09-21 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_bank_created_at_bank_created_by_bank_updated_at_and_more'),
        ('organizations', '0002_branch_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='organizations.branch', verbose_name='Cabang Terkait'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='organizations.branch', verbose_name='Cabang Terkait'),
        ),
    ]
