# Generated by Django 6.1 on 2026-08-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('LEAVE', 'Leave'), ('DOCUMENT', 'Document'), ('SYSTEM', 'System'), ('CRM', 'CRM & Sales'), ('OPS', 'Operasional'), ('FINANCE', 'Finance')], default='SYSTEM', max_length=20),
        ),
    ]
