# Generated by Django 6.1 on 2026-09-29 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notifikasi', 'verbose_name_plural': 'Notifikasi'},
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Pelaku Aksi'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, help_text='Tautan tujuan ketika notifikasi diklik', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ATTENDANCE', 'Kehadiran / HR'), ('LEAVE', 'Cuti / Izin'), ('DOCUMENT', 'Dokumen & Surat Jalan'), ('SYSTEM', 'Sistem & Keamanan'), ('CRM', 'CRM & Sales'), ('OPS', 'Operasional'), ('FINANCE', 'Finance & Keuangan'), ('MASTER', 'Data Master'), ('VM', 'Vendor Management')], default='SYSTEM', max_length=20),
        ),
    ]
